// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjxfgjqkunxbrharvfwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqeGZnanFrdW54YnJoYXJ2Znd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMjQzMTIsImV4cCI6MjA1MjYwMDMxMn0.WYTOrtaJs7V5nBk_Uj5pEh9qb1WBs7A5sErZBMuLMZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);